server:
  port: 6001 #端口号
spring:
  profiles: dev #测试环境
  applications:
    name: microservice-config-eureka
    
eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: false #禁用自我保护机制

---
server:
  port: 6001 #端口号
spring:
  profiles: prod #生产环境
  applications:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: true #开启自我保护机制*************

#保存时注意，选择UTF-8 保存 