spring:
  profiles:
    active: dev #激活开发环境配置
---
server:
  port: 4001
spring:
  profiles: dev #开发环境
  applications:
    name: microservice-config-dev
---
server:
  port: 4002 #端口号
spring:
  profiles: prod #开发环境
  applications:
    name: microservice-config-prod
#保存时注意,选择UTF-8保存
